"""Permanent redirects from the old WordPress.com URLs, as a Cloudflare Pages `_redirects` file.

Old links keep working, but every visitor and search engine is sent (301) to the
clean URL, so the WordPress date-style paths are retired rather than preserved.

Cloudflare limits: 2,000 static + 100 dynamic (splat) rules, first match wins,
and `/path` and `/path/` are different paths, so both are listed.
https://developers.cloudflare.com/pages/configuration/redirects/
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from . import urls
from .content import Site

MAX_STATIC = 2000
MAX_DYNAMIC = 100


@dataclass(frozen=True)
class Redirect:
    source: str
    destination: str
    status: int = 301

    @property
    def dynamic(self) -> bool:
        return "*" in self.source or ":" in self.source

    def line(self) -> str:
        return f"{self.source} {self.destination} {self.status}"


def _both(path: str, dest: str) -> list[Redirect]:
    """`/a/b/` and `/a/b`: Cloudflare matches them separately."""
    path = path.rstrip("/")
    return [Redirect(path + "/", dest), Redirect(path, dest)]


def build(site: Site, wordpress_urls: Path) -> list[Redirect]:
    old = json.loads(wordpress_urls.read_text(encoding="utf-8"))["comics"]
    by_number = {c.number: c for c in site.comics}
    static: list[Redirect] = []
    dynamic: list[Redirect] = []

    for entry in old:
        comic = by_number[entry["number"]]
        page = urls.comic(comic)
        static += _both(entry["post"], page)
        # WordPress also served an "attachment page" per image under the post URL.
        dynamic.append(Redirect(entry["post"].rstrip("/") + "/*", page))
        # Hotlinked originals (Reddit, forums, old blog posts) go to the same image here.
        for upload, img in zip(entry["uploads"], comic.images):
            static.append(Redirect(upload, urls.comic_image(img)))

    static += [
        Redirect("/wp-content/uploads/2014/01/2011_theme_bannerpng241.png", "/images/brand/banner.png"),
        *_both("/feed", urls.FEED),
        *_both("/feed/atom", urls.FEED),
        *_both("/feed/rss2", urls.FEED),
        *_both("/comments/feed", urls.FEED),
        *_both("/category/posts", urls.ARCHIVE),
        *_both("/author/samanthadegges", urls.ABOUT),
    ]
    # Catch-alls go last: first match wins.
    dynamic += [
        Redirect(f"/{prefix}/*", urls.ARCHIVE)
        for prefix in ("tag", "category", "page", "type", "2012", "2013", "2014")
    ]
    return static + dynamic


def render(redirects: list[Redirect]) -> str:
    static = sum(not r.dynamic for r in redirects)
    dynamic = len(redirects) - static
    if static > MAX_STATIC or dynamic > MAX_DYNAMIC:
        raise ValueError(f"{static} static / {dynamic} dynamic redirects exceeds Cloudflare's {MAX_STATIC}/{MAX_DYNAMIC} limit")
    header = (
        "# Generated by `python -m hardlyfunny build` from archive/wordpress_urls.json. Don't edit.\n"
        f"# {static} static + {dynamic} dynamic rules (Cloudflare allows {MAX_STATIC} + {MAX_DYNAMIC}).\n"
    )
    return header + "\n".join(r.line() for r in redirects) + "\n"
